### ISSUE TITLE
Bitter-Fit TODO

### ISSUE THREAD

**Issue by ericksonk** [The-Breakfast-Club/gui1#3]
- [ ]  a user can sign up and login (Jon)
  - [ ] `login.html`
         \* [ ] username, password, login button, sign up link
  - [ ] `signup.html`
         \* [ ] username, email, password, confirm password, sign-up button, login link
  - [ ] angular for connecting with the api
         \* [ ] can post new data to the api when a user signs up
         \* [ ] can login
- [ ] a user can create a new activity to track (Kristine)
  - [ ] `activity.html`
          \* [ ] title, date, number_of, units, edit button, add button
  - [ ] `add-activity.html`
  - [ ] activity form posts to user's activity page
         \* [ ] can post new activity to api
         \* [ ] new activity posts to activity page
- [ ] a user can view chart for activity for last 30 days
  - [ ] `chart.html`
- [ ] a user can edit a stat (if time??)
  - [ ] `edit-activity.html`
